# This is a basic workflow to audit dependencies
name: Audit Dependencies
run-name: ¡Audit Dependencies!

# Controls when the workflow will run
on:
  # Triggers the workflow on cron
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "audit"
  audit:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.11.1

      # 1) Install dependencies
      - name: Install dependencies
        run: npm i

      # 2) Audit dependencies
      - name: Run npm audit
        run: npm audit